const schedule = {
  "Monday": [
    { number: 1, subject: { ua: "Алгебра", pl: "Algebra" }, time: "9:00 - 9:45" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "9:45 - 9:55" },
    { number: 2, subject: { ua: "Biologia", pl: "Biologia" }, time: "9:55 - 10:40" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "10:40 - 10:50" },
    { number: 3, subject: { ua: "Польська мова", pl: "Język polski" }, time: "10:50 - 11:35" },
    { number: " ", subject: { ua: "Обід", pl: "Obiad" }, time: "11:35 - 11:55" },
    { number: 4, subject: { ua: "Англійська мова", pl: "Język angielski" }, time: "11:55 - 12:40" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "12:40 - 13:00" },
    { number: 5, subject: { ua: "Англійська мова", pl: "Język angielski" }, time: "13:00 - 13:45" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "13:45 - 13:55" },
    { number: 6, subject: { ua: "Fizyka", pl: "Fizyka" }, time: "13:55 - 14:40" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "14:40 - 14:50" },
    { number: 7, subject: { ua: "Українська мова", pl: "Język ukraiński" }, time: "14:50 - 15:35" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "15:35 - 15:45" },
    { number: 8, subject: { ua: "Українська література", pl: "Ukraińska literatura" }, time: "15:45 - 16:30" }
  ],
  "Tuesday": [
    { number: 1, subject: { ua: "Алгебра", pl: "Algebra" }, time: "9:00 - 9:45" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "9:45 - 9:55" },
    { number: 2, subject: { ua: "Англійська мова", pl: "Język angielski" }, time: "9:55 - 10:40" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "10:40 - 10:50" },
    { number: 3, subject: { ua: "Українська мова", pl: "Język ukraiński" }, time: "10:50 - 11:35" },
    { number: " ", subject: { ua: "Обід", pl: "Obiad" }, time: "11:35 - 11:55" },
    { number: 4, subject: { ua: "Англійська мова", pl: "Język angielski" }, time: "11:55 - 12:40" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "12:40 - 13:00" },
    { number: 5, subject: { ua: "Historia Polski", pl: "Historia Polski" }, time: "13:00 - 13:45" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "13:45 - 13:55" },
    { number: 6, subject: { ua: "Matematyka", pl: "Matematyka" }, time: "13:55 - 14:40" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "14:40 - 14:50" },
    { number: 7, subject: { ua: "Польська мова", pl: "Język polski" }, time: "14:50 - 15:35" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "15:35 - 15:45" },
    { number: 8, subject: { ua: "Польська мова", pl: "Język polski" }, time: "15:45 - 16:30" }
  ],
  "Wednesday": [
    { number: 1, subject: { ua: "Geografia", pl: "Geografia" }, time: "9:00 - 9:45" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "9:45 - 9:55" },
    { number: 2, subject: { ua: "Fizyka", pl: "Fizyka" }, time: "9:55 - 10:40" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "10:40 - 10:50" },
    { number: 3, subject: { ua: "Польська мова", pl: "Język polski" }, time: "10:50 - 11:35" },
    { number: " ", subject: { ua: "Обід", pl: "Obiad" }, time: "11:35 - 11:55" },
    { number: 4, subject: { ua: "Chemia", pl: "Chemia" }, time: "11:55 - 12:40" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "12:40 - 13:00" },
    { number: 5, subject: { ua: "Wychowanie fizyczne", pl: "Wychowanie fizyczne" }, time: "13:00 - 13:45" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "13:45 - 13:55" },
    { number: 6, subject: { ua: "Wychowanie fizyczne", pl: "Wychowanie fizyczne" }, time: "13:55 - 14:40" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "14:40 - 14:50" },
    { number: 7, subject: { ua: "Інформатика", pl: "Informatyka" }, time: "14:50 - 15:35" }
  ],
  "Thursday": [
    { number: 1, subject: { ua: "Chemia", pl: "Chemia" }, time: "9:00 - 9:45" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "9:45 - 9:55" },
    { number: 2, subject: { ua: "Польська мова", pl: "Język polski" }, time: "9:55 - 10:40" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "10:40 - 10:50" },
    { number: 3, subject: { ua: "Геометрія", pl: "Geometria" }, time: "10:50 - 11:35" },
    { number: " ", subject: { ua: "Обід", pl: "Obiad" }, time: "11:35 - 11:55" },
    { number: 4, subject: { ua: "Польська мова", pl: "Język polski" }, time: "11:55 - 12:40" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "12:40 - 13:00" },
    { number: 5, subject: { ua: "Historia Polski", pl: "Historia Polski" }, time: "13:00 - 13:45" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "13:45 - 13:55" },
    { number: 6, subject: { ua: "Historia Polski", pl: "Historia Polski" }, time: "13:55 - 14:40" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "14:40 - 14:50" },
    { number: 7, subject: { ua: "Факультатив з математики", pl: "Dodatkowe zajęcia z matematyki" }, time: "14:50 - 15:35" },
  ],
  "Friday": [
    { number: 1, subject: {  ua: "Математика", pl: "Matematyka" }, time: "9:00 - 9:45" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "9:45 - 9:55" },
    { number: 2, subject: { ua: "Історія України", pl: "Historia Ukrainy" }, time: "9:55 - 10:40" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "10:40 - 10:50" },
    { number: 3, subject: { ua: "Історія України", pl: "Historia Ukrainy" }, time: "10:50 - 11:35" },
    { number: " ", subject: { ua: "Обід", pl: "Obiad" }, time: "11:35 - 11:55" },
    { number: 4, subject: { ua: "Англійська мова", pl: "Język angielski" }, time: "11:55 - 12:40" },
    { number: " ", subject: { ua: "Перерва", pl: "Przerwa" }, time: "12:40 - 13:00" },
    { number: " ", subject: { ua: "Очікування автобуса", pl: "Oczekiwanie na autobus" }, time: "13:00 - 13:20" },
    { number: " ", subject: { ua: "Шлях зі школи на басейн автобусом", pl: "Droga ze szkoły na basen autobusem" }, time: "13:20 - 13:45" },
    { number: 6, subject: { ua: "Фізичне виховання (басейн)", pl: "Wychowanie fizyczne (basen)" }, time: "14:00 - 15:00" },
    { number: " ", subject: { ua: "Шлях з басейну до школи автобусом", pl: "Droga z basenu do szkoły autobusem" }, time: "15:30 - 16:00" }
  ]
};

const dayNames = {
  "Monday": { ua: "Понеділок", pl: "Poniedziałek" },
  "Tuesday": { ua: "Вівторок", pl: "Wtorek" },
  "Wednesday": { ua: "Середа", pl: "Środa" },
  "Thursday": { ua: "Четвер", pl: "Czwartek" },
  "Friday": { ua: "П’ятниця", pl: "Piątek" }
};
